### ISSUE TITLE
Not working for LOS4MicroG

### ISSUE THREAD

**Issue by ghost** [timschumi/lineage-build-archiver#1]
Found this script on the LOS subreddit, and I've been using it ever since. For the LineageOS server it works fine, however when I run it on the LOS4MicroG server (off course with their pubkey) it just throws an error. I have the same issue with multiple devices, and on both 18.1 and 19.1. 

The error I get is:

Traceback (most recent call last):
  File "/home/gertjan/archiver-microg/download.py", line 159, in <module>
    sys.exit(main())
  File "/home/gertjan/archiver-microg/download.py", line 91, in main
    data = r.json()['response']
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I saw someone else having the same issue on Reddit, however it seems that he/she didn't find a solution, or at least not posted the solution. 

It must be a error with the script somehow not parsing the LOS4MicroG server or something. Would it be possible to support tht project too, since IMO it gives better right to the amazing LineageOS project.

**Comment by timschumi** [comment]
Are you sure that you are querying the correct server? What does the command that you are running look like?

**Comment by ghost** [comment]
I run it like this:

``python3 archiver-microg/download.py --output /home/gertjan/archiver-microg-output/LOS4MicroG --updater https://lineage.microg.org --key archiver-microg/update_verifier/lineageos4microg_pubkey --retain 4``

**Comment by timschumi** [comment]
You are apparently querying a device that does not exist on their server, and they are using a faulty server that doesn't respond properly when querying a nonexistent device (HTTP code 200, no JSON). That is an issue that you need to take up with them.
