### ISSUE TITLE
REQUEST: Include CyanogenMod also

### ISSUE THREAD

**Issue by reukiodo** [timschumi/lineage-build-archiver#4]
Firstly, I thank you for your efforts to preserve the last builds of many devices. Something that I wish was inherent to the Lineage project.

As Lineage came from CyanogenMod, and many older devices never received a Lineage build, I have some builds of older CyanogenMod-only devices that would be great to be included here for archival.

**Comment by timschumi** [comment]
As much as I regret it, archiving CyanogenMod builds is out of scope for this project.

The builds were signed with publicly-known keys (so there is no real way for me to verify the legitimacy of provided builds), and given that there won't be any new builds that appear it is also unnecessary to hook them up to an automated archive.

If you have any builds present locally, I would just recommend to upload them to [archive.org](https://archive.org). You also have my blessing (not that you'd need it) to modify the `lineage-build-archiver` to accommodate a static set of CyanogenMod builds and host the index yourself, if you desire to do so.

**Comment by reukiodo** [comment]
Is there an estimate of total space required for a full archive of what is already present?

**Comment by timschumi** [comment]
For the LineageOS archive, all builds that are currently archived sum up to 2618 Gigabytes. Archiving one of each device and version would take approximately 1107 Gigabytes (although I should probably update the calculation, the average build size is heavily skewed by now). Archiving all build that the archive has ever known to exist (i.e. ones that were on disk at some point but pruned) would take 19106 Gigabytes.

For a potential CyanogenMod archive I have no data, those builds are scattered all over the internet. The average build size was probably also a lot smaller back then.

**Comment by timschumi** [comment]
Updated the size calculation, archiving one of each™ build for LineageOS would currently take 925 Gigabytes.

As for CyanogenMod, judging by [multiple](https://archive.org/details/cyanogenmod-archive) [archives](https://archive.org/details/2016.cyanogenmod.org.snapshot), the size would end up somewhere between 868 Gigabytes and 1513 Gigabytes, plus whatever is available on the [WayBack Machine](https://web.archive.org/web/20161224211625/https://download.cyanogenmod.org/) and in other third-party archives.

**Comment by reukiodo** [comment]
Thanks! That seems like a doable project.
